In [5]:
from joblib import load
import numpy as np

In [2]:
model = load('iris_model.joblib')

In [3]:
model

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [4]:
model.classes_

array([0, 1, 2])

In [6]:
X = np.random.random((10, 4))

In [8]:
X

array([[0.62004246, 0.85053437, 0.98511556, 0.97153186],
       [0.76760489, 0.54242483, 0.25635612, 0.47765818],
       [0.0587347 , 0.15987858, 0.87920752, 0.44893289],
       [0.89314463, 0.25343914, 0.14144034, 0.12560134],
       [0.65297959, 0.50609273, 0.17180454, 0.25048495],
       [0.72306736, 0.75978416, 0.78584088, 0.64797615],
       [0.44068478, 0.81525565, 0.46938685, 0.69066239],
       [0.19345125, 0.49784324, 0.32417758, 0.05039966],
       [0.98059664, 0.94237983, 0.90729358, 0.9675631 ],
       [0.13548063, 0.08429963, 0.31838923, 0.37347498]])

In [9]:
model.predict(X)

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0])