In [1]:
from joblib import load


In [2]:
model = load('sentiment_model.joblib')

In [3]:
model

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [4]:
model.classes_

array(['neg', 'pos'], dtype='<U3')

In [5]:
model.get_params()

{'alpha': 1.0, 'binarize': 0.0, 'class_prior': None, 'fit_prior': True}

In [6]:
model.coef_

array([[-9.20170318, -6.3395023 , -9.20170318, ..., -9.89485036,
        -9.20170318, -9.89485036]])

In [7]:
X = [
    'I love this movie, such a great actors',
    'This movie sucks. My whole family hates it'
]

In [8]:
vect = load('sentiment_vectorizer.joblib')
X = vect.transform(X)
X

<2x39659 sparse matrix of type '<class 'numpy.int64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [9]:
model.predict(X)

array(['neg', 'neg'], dtype='<U3')

In [10]:
vect.get_feature_names()[2000:2050]

['anvil',
 'anway',
 'anxieties',
 'anxiety',
 'anxious',
 'anxiously',
 'any',
 'anya',
 'anybody',
 'anyhoo',
 'anyhow',
 'anymore',
 'anyone',
 'anything',
 'anytime',
 'anytown',
 'anyway',
 'anyways',
 'anywhere',
 'aoki',
 'aol',
 'ap2',
 'apace',
 'apaches',
 'apart',
 'apartheid',
 'apartment',
 'apartments',
 'apathetic',
 'apathy',
 'ape',
 'aped',
 'aperitif',
 'apes',
 'apex',
 'apfelschnitt',
 'aphrodiasiatic',
 'aphrodite',
 'aplenty',
 'aplomb',
 'apocalypse',
 'apocalyptic',
 'apollo',
 'apollonia',
 'apologetic',
 'apologetically',
 'apologies',
 'apologize',
 'apologizes',
 'apologizing']

In [13]:
X[0].todense()

matrix([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [14]:
vect.inverse_transform(X)

[array(['actors', 'great', 'love', 'movie', 'such', 'this'], dtype='<U58'),
 array(['family', 'hates', 'it', 'movie', 'my', 'sucks', 'this', 'whole'],
       dtype='<U58')]

In [15]:
model.predict(X)

array(['neg', 'neg'], dtype='<U3')

In [16]:
model.predict_proba(X)

array([[0.69654128, 0.30345872],
       [0.9769404 , 0.0230596 ]])